# Generated by Django 4.2.5 on 2023-10-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actividad_ep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('periodicidad', models.CharField(max_length=30)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripción', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dirección', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('dependencia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='infra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('tamaño', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
