# Generated by Django 4.2.5 on 2023-10-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colegio',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
