# Generated by Django 4.2.5 on 2023-10-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0002_rename_dirección_colegio_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beca',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
